### ISSUE TITLE
Code no longer builds

### ISSUE THREAD

**Issue by rbradcurtis** [danieloneill/nodeevdev#1]
Sorry to dig up an old repo!

Checking to see if you have an updated (offline) version of this code that can be committed before I spend time 'fixing' it.

This build is on a stock Ubuntu 22.04 / LTS server.  This error is pretty easy, as uv.h is stored elsewhere nowadays, but it opens the door to (many) more build errors. . .

```
user@server:~/dev/nodeevdev$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/dev/nodeevdev/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/dev/nodeevdev',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/dev/nodeevdev/build'
  CXX(target) Release/obj.target/evdev/src/evdev.o
In file included from ../src/evdev.cpp:15:
../src/evdev.h:8:10: fatal error: node/uv.h: No such file or directory
    8 | #include <node/uv.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [evdev.target.mk:113: Release/obj.target/evdev/src/evdev.o] Error 1
make: Leaving directory '/home/user/dev/nodeevdev/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.15.0-27-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/dev/nodeevdev
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

```

**Comment by danieloneill** [comment]
I'm afraid not! I haven't used node since shortly after I made these bindings half a decade ago.

I may spend a weekend of loud music and coolers bringing them up to modern node standards, but I can't promise anything. It's difficult for me to dedicate time to maintain a tool I don't use, particularly when there isn't much interest in it generally.  🤷

If you do update it before I do, please let me know how that goes.
